### ISSUE TITLE
Email Not Sending When Specific Categories are Selected

### ISSUE THREAD

**Issue by mrjarbenne** [hwdsb/subscribe-by-email#1]
Sending content from all categories works, but the functionality that should allow the plugin to only send out content specifically categorized seems to not be functioning. When anything other than **All** is selected, the plugin fails to send out any notifications. 

![2019-09-04_17-11-45](https://user-images.githubusercontent.com/480667/64291954-4e943f00-cf37-11e9-9c5e-15bb7fee4681.png)

**Comment by r-a-y** [comment]
This bug is only applicable to Gutenberg.

Do we want to support both Classic Editor and the Block Editor?  Or just the Block Editor?  If just the Block Editor, then commit 82e1e68 should fix this.  I haven't pushed this to production yet.

**Comment by mrjarbenne** [comment]
Will the old editor still support sending All Categories, or does this fix break the functionality in the old editor all together? Either way I’m good with just supporting the new editor, but the messaging out to the users will be different.

**Comment by r-a-y** [comment]
The previous commit fixed category emails for Gutenberg, but broke support for Classic Editor.

Latest commit adds back support for Classic Editor, while retaining support for Gutenberg.  Have to code for both instances.

Added the code to production for testing and ran some tests on the `sandbox` sub-site.  Appears to be working.  Let me know if you encounter any bugs.

**Comment by mrjarbenne** [comment]
I've heard back from a few users. It looks like this is working now. Thanks for the fix.
