### ISSUE TITLE
Widget Doesn't Work

### ISSUE THREAD

**Issue by mrjarbenne** [hwdsb/subscribe-by-email#2]
The Subscribe by Email widget hangs when you hit the Subscribe button, not allowing users to subscribe to blogs. The follow tab that can be added to the bottom of the site works, and the shortcode [subscribe-by-email-form autopt="false"] works when placed in blog content, or when inserted into a text widget. 

The sidebar widget must use different logic that is triggering a jquery error.

![2019-09-06_08-44-33](https://user-images.githubusercontent.com/480667/64429931-1b5fc600-d085-11e9-834d-2515f02bf6ea.png)

**Comment by mrjarbenne** [comment]
@r-a-y can you take a look into this. There seems to be a discrepency between how the Widget works in comparison to the shortcode and the slider menu. Of course it's the Widget that everyone uses.

![2019-09-20_14-26-07](https://user-images.githubusercontent.com/480667/65349998-b80c8280-dbb2-11e9-90be-cf9f495344b2.png)

**Comment by r-a-y** [comment]
The problem is due to bad code during the widget AJAX validation routine.

I've fixed this in the `widget-fixes` branch here:
- commit 09001d312921dc954ce118b7e8c96df6eb38385e
- commit e51875ca911119b0f4a6a7f65af89b68ad205f22
- commit 4c9bd4953a18b5f379bf0d719a95fa81feb86a34

**Comment by r-a-y** [comment]
Also one other point to note is the code on production is different that the one in this repo.  I'm guessing wpmudev updated their code for their plugin to their customers, but not on their Github repo.

**Comment by mrjarbenne** [comment]
Hmmm. I wonder which is more up to date? I know I was juggling two versions when I was initially trying to sort out this issue (an old one from wpmu, and this repo) I’ll try to find the one in production and sort out which one looks like a better bet to move forward with.

**Comment by mrjarbenne** [comment]
The one in this repo has some re-captcha changes that don't seem to be in the older version I have from WPMU. So this looks like a newer version (not that this ensures it's better). 

I'll defer to you -- in as much as you can assess a plugin that you didn't code yourself -- which version do you think we should move forward with?

**Comment by mrjarbenne** [comment]
I just created a new branch called prod-branch to compare the two instances of the plugin. Other than the translation changes I hadn't pushed yet, and the changes that you've just made, I'm not seeing the differences you are referring to. That said, you may have replaced the older different  plugin with the one from this repo, with your changes, which works too.

**Comment by r-a-y** [comment]
Yeah, you're right.  When I was applying the changes to Github, there were some markup changes for the widget, but they were minor.

I must have replaced the widget code on production with the one in my `widget-fixes` branch.

**Comment by mrjarbenne** [comment]
Ok. I'll fix the branches up to clean up some of the code so we just have a nice master branch. Looks good. Widgets are fixed. Thanks.
