### ISSUE TITLE
Errors in Database

### ISSUE THREAD

**Issue by mrjarbenne** [hwdsb/subscribe-by-email#3]
There are a number of database errors popping up in the debug.log file related to this plugin. @r-a-y could you possibly take a look and see if there is something at the plugin site that might be causing them: 

E.g.: 

`[09-Mar-2020 08:02:12 UTC] WordPress database error Deadlock found when trying to get lock; try restarting transaction for query DELETE FROM `wp_options` WHERE `option_name` = '_transient_timeout_sbe_pending_mails_sent' made by require('wp-blog-header.php'), require_once('wp-load.php'), require_once('wp-config.php'), require_once('wp-settings.php'), do_action('init'), WP_Hook->do_action, WP_Hook->apply_filters, Incsub_Subscribe_By_Email->init_plugin, Incsub_Subscribe_By_Email->maybe_send_pending_emails, get_transient, delete_option`

`[13-Mar-2020 14:32:49 UTC] WordPress database error Unknown column 'campaign_hash' in 'field list' for query INSERT INTO `wp_3178_subscriptions_log_table` (`mail_subject`, `mail_recipients`, `mail_date`, `mail_settings`, `max_email_ID`, `campaign_hash`) VALUES ('', 0, 1584095569, 'a:1:{s:9:\"posts_ids\";a:1:{i:0;i:12499;}}', 12343, '4b6d46a61fda8b207ce07fc0c67f641f') made by require('wp-blog-header.php'), wp, WP->main, WP->parse_request, do_action_ref_array('parse_request'), WP_Hook->do_action, WP_Hook->apply_filters, rest_api_loaded, WP_REST_Server->serve_request, WP_REST_Server->dispatch, WP_REST_Posts_Controller->update_item, do_action('rest_after_insert_post'), WP_Hook->do_action, WP_Hook->apply_filters, Incsub_Subscribe_By_Email->process_instant_subscriptions_for_gutenberg, Incsub_Subscribe_By_Email->enqueue_emails, incsub_sbe_insert_campaign`

**Comment by r-a-y** [comment]
The `campaign_hash` error should be fixed now. The `subscribe-by-email` plugin did not update the subscription log table's schema for the main site and site ID 3178.  I just manually ran the upgrade routine for those two sites and it should be fixed now.

The deadlock one is harder to pinpoint, but I'll do a bit more research.

**Comment by mrjarbenne** [comment]
There might be other sites that didn’t update. Did you want me to pour through the debug log to see? Those errors in the issue were two random examples I grabbed from a large chunk.

**Comment by r-a-y** [comment]
Those were the only two sites according to the debug log.

**Comment by mrjarbenne** [comment]
You rock.
