### ISSUE TITLE
Scheduled Posts Don't Get Sent

### ISSUE THREAD

**Issue by mrjarbenne** [hwdsb/subscribe-by-email#4]
Hi @r-a-y. It looks like when teachers schedule their posts, it's not triggering an email, and it's not showing up in the batch of pending emails. 

Posts published immediately work, regardless of whether I have the subscription settings set to immediately publish the email blast, or to schedule the email blast as a digest. It's just if the post itself is scheduled to run in the future that it's not triggering the email subscription settings.

**Comment by mrjarbenne** [comment]
I wonder if it's an issue with our cron settings. Other plugins that provide similar functionality require some tweaking to the cron settings in order to work: 

https://www.icegram.com/documentation/es-how-to-schedule-cron-emails-in-cpanel/

**Comment by r-a-y** [comment]
Is this a new occurrence or is this an old bug?

About cron, WordPress cron doesn't run on a typical cron job, it relies on traffic from regular users to trigger the emails. I don't believe `subscribe-by-email` allows you to set a custom cron job that a real server could use.

I'll take a closer look in the next day or so.

**Comment by mrjarbenne** [comment]
Honestly I don’t know. I never schedule posts, and it’s the first time it’s been reported. I tried to trigger it by visiting the site shortly after the post had been scheduled to be published, and it didn’t fire. This method of triggering it through traffic does work if you publish immediately and schedule the digest in the future, but doesn’t seem to trigger an email for a post that was scheduled to fire. 

Thanks for looking.

**Comment by r-a-y** [comment]
Looks like I caused this bug when trying to fix category posts (#1). 🤦‍♂️ 

Should work now, I tested locally with the block editor. Can you give it a try?

**Comment by mrjarbenne** [comment]
I just tested this on sandbox.commons.hwdsb.on.on.ca, which we are both subscribed to, but it didn't seem to fire.

**Comment by r-a-y** [comment]
I just tested this and it works. The problem is with Sandbox, the SBE settings were set to send only for the "Art" category.

**Comment by mrjarbenne** [comment]
ARGGH. Sorry about that. I see the post from the future in my inbox. Thanks for the fix.
