### ISSUE TITLE
Category Selection Not Functioning and Email Not Sent

### ISSUE THREAD

**Issue by mrjarbenne** [hwdsb/subscribe-by-email#5]
Separate but potentially related issue. 

When selecting a category via the Settings/Content tab, the check boxes are no longer rendering a checkmark, and the different Post types are not appearing as options (previously Events appeared as an option on sites that had the Events Calendar plugin active)

https://sandbox.commons.hwdsb.on.ca/wp-admin/admin.php?page=sbe-settings&tab=content

Investigating reports that email is not being sent from the site. There are a number of errors in the logs from various wp_#### instances in the database.

Example: 

`[01-Sep-2020 08:02:32 UTC] WordPress database error Deadlock found when trying to get lock; try restarting transaction for query DELETE FROM `wp_1477_options` WHERE `option_name` = '_transient_sbe_pending_mails_sent' made by require('wp-blog-header.php'), require_once('wp-load.php'), require_once('wp-config.php'), require_once('wp-settings.php'), do_action('init'), WP_Hook->do_action, WP_Hook->apply_filters, Incsub_Subscribe_By_Email->init_plugin, Incsub_Subscribe_By_Email->maybe_send_pending_emails, get_transient, delete_option`

**Comment by r-a-y** [comment]
The "Settings > Contents" page is rendering correctly again. Had to rewrite parts of the JS and fix how SBE was querying for the post types. SBE was fetching the post types too early, so not all post types could be recognized at run-time.

I haven't looked into the email issue yet.

**Comment by mrjarbenne** [comment]
Email issue looks like it might be on the server side. Stay tuned.
