### ISSUE TITLE
Move "Do Not Send This Post" Metabox to Sidebar

### ISSUE THREAD

**Issue by mrjarbenne** [hwdsb/subscribe-by-email#6]
Although the code looks to be pointing at the sidebar, the metabox is still appearing in the "normal" position. 

https://github.com/hwdsb/subscribe-by-email/blob/3fc243c50dceeaa795cd93a38ec088b17f594df3/admin/meta-boxes/do-not-send-meta-box.php#L19

<img width="1086" alt="2021-06-21_21-15-36" src="https://user-images.githubusercontent.com/480667/122847583-fa0daf80-d2d5-11eb-8d31-92399d9ffa48.png">

Any ideas what might be over-riding this line @r-a-y?

**Comment by r-a-y** [comment]
Hmm, it's displaying correctly for me on the Sandbox site.

Did you previously use the Classic Editor to move the SBE metabox to the main column and then switched back to the Block Editor later on?

Read the following article for a detailed breakdown: https://www.intelliwolf.com/move-wordpress-meta-box-from-sidebar/

**Comment by mrjarbenne** [comment]
No, this was a brand new blog I hadn't done anything with yet, and the meta-box was as pictured. 

I'll try to drag it around.

**Comment by r-a-y** [comment]
Metabox order is saved for each user in the `meta-box-order_post` option.

I just checked your metabox order and your SBE metabox was saved to the `normal` position. Whereas, for me, it is saved to the `side` position.

I've just updated your meta box order so SBE is now on the side. Also, I saw the metabox for Beehive was saved in the `normal` position. I believe that is correct, but let me know if you want me to move that to the `side` position.

**Comment by mrjarbenne** [comment]
Ok, so somewhere along the line maybe I moved it and it sticks for subsequent subdomains. 

Seems like you can drag items from Normal over to sidebar, but you can't drag it back once it's in the sidebar without the classic editor plugin as per that link you shared (which is active, enforcing the new editor except in a couple instances, but not something I want to make available to end users) 

Sounds like this is a user-by-user selection and not something we can enforce. I'll just instruct people to drag the box over to the sidebar. Thanks for looking into it.

**Comment by r-a-y** [comment]
> Sounds like this is a user-by-user selection and not something we can enforce.

Actually, if we want to enforce the SBE metabox to the side, it should be possible with filters. Do we only want to do this for the Block Editor?

**Comment by mrjarbenne** [comment]
If we could force it to the side that would be great. Yes: block editor only.

**Comment by r-a-y** [comment]
I've forced the display of the metabox to the side when using the Block Editor. When switching back to Classic Editor, the metabox should display back in the main column if it was set there to begin with.
